language: cpp

compiler:
    - gcc
    - clang

os:
    - linux
    - osx

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install binutils; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir bin tmp; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (cd bin && ln -s `which gobjcopy` objcopy); fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=`pwd`/bin:${PATH}; fi

script:
    - make
    - ./hello > tmp/hello.out
    - diff tmp/hello.out test/fixture.out
