language: cpp

compiler:
    - gcc

os:
    - linux
    - osx

before_script:
    - brew install binutils
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=`pwd`/bin:${PATH}; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir bin; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd bin && ln -s `which gobjcopy` objcopy; fi

script:
    - make

#install:
#   - sudo make install
