language: cpp

compiler:
    - gcc

os:
    - linux

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (mkdir bin; cd bin; ln -s `which gobjcopy` objcopy); fi

script:
    - make

#install:
#   - sudo make install
