language: cpp

compiler:
    - gcc

os:
    - linux
    - osx

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (export PATH=`pwd`/bin:${PATH}; mkdir bin; cd bin; ln -s `which gobjcopy` objcopy); fi

script:
    - make

#install:
#   - sudo make install
