language: cpp

compiler:
    - gcc
    - clang

os:
    - linux
    - osx

before_script:
    - mkdir tmp
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install binutils; fi
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then mkdir bin; fi
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then (cd bin && ln -s `which gobjcopy` objcopy); fi
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then export PATH=`pwd`/bin:${PATH}; fi

script:
    - make
    - ls -l
    - ldd ./hello
    - ./hello > tmp/hello.out
    - pwd
    - od -H test/unix/fixture.out
    - od -H test/mac/fixture.out
    - od -H test/win/fixture.out
    - od -H tmp/hello.out
#   - if [[ "${TRAVIS_OS_NAME}" == "osx"   ]]; then diff tmp/hello.out test/mac/fixture.out;  fi
#   - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then diff tmp/hello.out test/unix/fixture.out; fi
#   - if [[ "${TRAVIS_OS_NAME}" == "win"   ]]; then diff tmp/hello.out test/win/fixture.out;  fi
#   - find . | xargs ls -l
