language: cpp

compiler:
    - gcc
    - clang

os:
    - linux
    - osx

before_script:
    - mkdir tmp
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install binutils; fi
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then mkdir bin; fi
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then (cd bin && ln -s `which gobjcopy` objcopy); fi
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then export PATH=`pwd`/bin:${PATH}; fi

script:
    - make
    - src/hello.full > tmp/hello.out
    - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then diff tmp/hello.out test/unix/fixture.out; fi
    - if [[ "${TRAVIS_OS_NAME}" == "osx"   ]]; then diff tmp/hello.out test/unix/fixture.out; fi
    - if [[ "${TRAVIS_OS_NAME}" == "win"   ]]; then diff tmp/hello.out test/win/fixture.out;  fi
