matrix:
    include:
        - language: cpp
          compiler: gcc
          os: linux
          dist: trusty
          sudo: required
          before_script:
              - mkdir tmp
              - git clone git://github.com/davisking/dlib.git
              - (mkdir dlib/build && cd dlib/build && cmake .. && cmake --build . && cmake --build . --target install)
              - (cd dlib/build && sudo make install)
          script:
              - make
              - src/hello > tmp/hello.out
              - diff tmp/hello.out test/unix/fixture.out

        - language: cpp
          compiler: clang
          os: linux
          dist: trusty
          sudo: required
          before_script:
              - mkdir tmp
              - git clone git://github.com/davisking/dlib.git
              - (mkdir dlib/build && cd dlib/build && cmake .. && cmake --build . && cmake --build . --target install)
              - (cd dlib/build && sudo make install)
          script:
              - make
              - src/hello > tmp/hello.out
              - diff tmp/hello.out test/unix/fixture.out

        - language: cpp
          compiler: gcc
          os: linux
          dist: precise
          sudo: required
          before_script:
              - mkdir tmp
              - git clone git://github.com/davisking/dlib.git
              - (mkdir dlib/build && cd dlib/build && cmake .. && cmake --build . && cmake --build . --target install)
              - (cd dlib/build && sudo make install)
          script:
              - make
              - src/hello > tmp/hello.out
              - diff tmp/hello.out test/unix/fixture.out

        - language: cpp
          compiler: clang
          os: linux
          dist: precise
          sudo: required
          before_script:
              - mkdir tmp
              - git clone git://github.com/davisking/dlib.git
              - (mkdir dlib/build && cd dlib/build && cmake .. && cmake --build . && cmake --build . --target install)
              - (cd dlib/build && sudo make install)
          script:
              - make
              - src/hello > tmp/hello.out
              - diff tmp/hello.out test/unix/fixture.out

        - language: cpp
          compiler: gcc
          os: osx
          before_script:
              - mkdir tmp
              - brew install binutils
              - mkdir bin
              - (cd bin && ln -s `which gobjcopy` objcopy)
              - export PATH=`pwd`/bin:${PATH}
              - git clone git://github.com/davisking/dlib.git
              - (mkdir dlib/build && cd dlib/build && cmake .. && cmake --build . && sudo cmake --build . --target install)
          script:
              - make
              - src/hello.full > tmp/hello.out
              - diff tmp/hello.out test/unix/fixture.out

        - language: cpp
          compiler: clang
          os: osx
          before_script:
              - mkdir tmp
              - brew install binutils
              - mkdir bin
              - (cd bin && ln -s `which gobjcopy` objcopy)
              - export PATH=`pwd`/bin:${PATH}
              - git clone git://github.com/davisking/dlib.git
              - (mkdir dlib/build && cd dlib/build && cmake .. && cmake --build . && sudo cmake --build . --target install)
          script:
              - make
              - src/hello.full > tmp/hello.out
              - diff tmp/hello.out test/unix/fixture.out
