PROG_CXX = hello
SRCS     = main.cc opt.cc server.cc
INCS     = opt.hpp server.hpp
MK_MAN   = no

CXXFLAGS += -I../dlib
CXXFLAGS += -std=c++11 -pthread

LDADD    += -L../dlib/build/dlib -ldlib

.include <bsd.prog.mk>
